apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-quarkus
  namespace: demo
  labels:
    app: demo-app-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-quarkus
  template:
    metadata:
      labels:
        app: demo-app-quarkus
    spec:
      imagePullSecrets:
        - name: regcred-harbor
      containers:
        - name: quarkus
          image: registry.navy.kubezt.com/ccravens/demo-app-quarkus@sha256:b866927c4ee40b0cbacece75195419aa271a1b52041365ef8b562b66c7b3112a
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
