apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-quarkus
  namespace: demo
  labels:
    app: demo-app-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-quarkus
  template:
    metadata:
      labels:
        app: demo-app-quarkus
    spec:
      imagePullSecrets:
        - name: regcred-harbor
      containers:
        - name: quarkus
          image: registry.dev.kubezt.com/ccravens/demo-app-quarkus@sha256:a6ca9ce56cc2243da134545b3ac9e4c6af0ba60029c5fbe3a5f4212f7944f62f
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
