apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-quarkus
  namespace: demo
  labels:
    app: demo-app-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-quarkus
  template:
    metadata:
      labels:
        app: demo-app-quarkus
    spec:
      imagePullSecrets:
        - name: regcred-harbor
      containers:
        - name: quarkus
          image: registry.navy.kubezt.com/ccravens/demo-app-quarkus@sha256:bf949695c6dbf40e64a440cbe03367e219085e45fd86b3c4e93e79df1c1f267b
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
